seed:-1
exp_name:train_everything_init_rand_abst_500000
debug:False
data_path:/home/rogupta/wikinet_2/data
yamada_model:yamada_model.pickle
num_shards:300
gram_type:trigram
gram_vocab:vocab_trigram_266826.tsv
train_size:500000
query_size:5000
conll_split:dev
max_word_size:5
max_gram_size:40
max_context_size:200
max_ent_size:60
include_word:False
include_gram:True
gram_lower:True
include_context:True
model:combined
init_rand:True
norm_gram:True
norm_word:True
norm_context:True
norm_final:False
cand_gen_rand:False
num_candidates:60
patience:2
num_epochs:10
batch_size:16
num_workers:8
gram_dim:64
margin:0.5
loss_func:cross_entropy
measure:ip
lr:1e-03
wd:1e-04
optim:adagrad
sparse:False
train_ent:True
train_word:True
train_linear:True
train_gram:True
device:1