# General
seed:-1
exp_name:autoencoder
debug:False

# Data
data_path:/work/rogupta/wikinet_data
yamada_model:yamada_model.pickle
data_type:proto
train_size:10000000
eval_sample:10000

# Max padding
max_char_size:40

# Model Params
dp:0.2
char_dim:8
hidden_size:64
norm:True
activate:n
measure:ip

# Training Settings
num_epochs:100
batch_size:1000000
lr:1e-03
wd:1e-06

# Cuda
use_cuda:True
device:0
