# General
seed:-1
exp_name:full_context_string
debug:False

# Data
data_path:/work/rogupta/wikinet_data
data_type:proto
num_shards:100
train_size:10000000
query_size:5000
conll_split:dev
yamada_model:yamada_model.pickle

# Gram Settings
gram_type:trigram
gram_lower:True
gram_dim:64

# Max padding
max_word_size:5
max_gram_size:35
max_context_size:100
max_char_size:40
max_ent_size:35

# Model types
model_name:linear

# Model Embs
init_context_embs:yamada
init_mention_embs:random
init_char_embs:/work/rogupta/wikinet_data/autoencoder/max_char_40_hidden_32.ckpt
mention_word_dim:128
mention_ent_dim:128
context_word_dim:128

# Model hyperparams
dp:0.2
measure:ip
combined_linear:True
init_stdv:0.01

# Normalization
norm_final:True

# Candidate Generation
cand_gen_rand:False
num_candidates:256

# Training Settings
patience:5
num_epochs:20
batch_size:32
num_workers:8
lr:1e-03
wd:1e-06
optim:adagrad
save_every:5

# Loss
margin:0.5
loss_func:cross_entropy

# Things to train
train_ent:True
train_word:True
train_mention:True
train_linear:True
train_gram:True

# Cuda
use_cuda:True
device:0
