# General
seed:-1
exp_name:combined_train_conll_train_gram
debug:False

# Data
data_path:/home/rogupta/wikinet_2/data
data_type:conll
num_shards:300
train_size:500000
query_size:5000
conll_split:dev
yamada_model:yamada_model.pickle

# Gram Settings
gram_type:trigram
gram_lower:True
gram_vocab:vocab_trigram_266826.tsv
gram_dim:64
mention_word_dim:0

# Max padding
max_word_size:5
max_gram_size:40
max_context_size:200
max_ent_size:60

# Model types
model:combined
init_rand:False
## Combined
include_word:False
include_gram:True
include_context:True
include_mention:False
weigh_concat:False
## Yamada
include_string:False
include_stats:False

# Model Params
## Combined
measure:ip
## Yamada
dp:0
hidden_size:1000

# Normalization
norm_gram:True
norm_word:True
norm_mention:False
norm_context:True
norm_final:False

# Candidate Generation
cand_gen_rand:False
num_candidates:32

# Training Settings
patience:2
num_epochs:10
batch_size:32
num_workers:8
lr:1e-03
wd:1e-04
optim:adagrad
sparse:False
save_every:5

# Loss
margin:0.5
loss_func:cross_entropy

# Things to train
train_ent:False
train_word:False
train_mention:False
train_linear:False
train_gram:True
