seed:-1
verbose:False
debug:False
data_path:/home/rogupta/wikinet_2/data
yamada_model:ntee_300_sentence.pickle
num_shards:100
gram_type:trigram
gram_vocab:vocab_trigram_266826.tsv
training_size:100000
query_size:5000
max_word_size:5
max_gram_size:40
max_context_size:200
max_ent_size:60
include_word:False
norm_gram:False
norm_word:False
norm_context:True
norm_final:True
cand_gen_rand:True
num_epochs:10
batch_size:32
num_workers:8
gram_dim:32
margin:0.5
l2:1e-02
wd:1e-04
optim:adagrad