seed:-1
exp_name:true_everything_train_everything_dim
debug:False
data_path:/home/rogupta/wikinet_2/data
yamada_model:ntee_300_sentence.pickle
num_shards:100
gram_type:trigram
gram_vocab:vocab_trigram_266826.tsv
train_size:100000
query_size:5000
conll_split:dev
max_word_size:5
max_gram_size:40
max_context_size:200
max_ent_size:60
include_word:True
include_gram:True
include_context:True
norm_gram:True
norm_word:True
norm_context:True
norm_final:True
cand_gen_rand:True
num_candidates:32
patience:2
num_epochs:10
batch_size:32
num_workers:8
gram_dim:64
margin:0.5
loss_func:cross_entropy
measure:ip
lr:1e-03
wd:1e-04
optim:adagrad
sparse:False
train_ent:Train
train_word:Train
train_linear:Train
train_gram:True
device:0