seed:-1
exp_name:weigh_concat
debug:False
data_path:/home/rogupta/wikinet_2/data
yamada_model:yamada_model.pickle
num_shards:1000
gram_type:trigram
gram_vocab:vocab_trigram_266826.tsv
train_size:5000000
query_size:5000
conll_split:dev
max_word_size:5
max_gram_size:40
max_context_size:200
max_ent_size:60
include_word:False
include_gram:True
gram_lower:True
include_context:True
include_mention:False
weigh_concat:True
model:combined
norm_gram:True
norm_word:True
norm_context:True
norm_final:False
norm_mention:True
cand_gen_rand:False
num_candidates:32
patience:2
num_epochs:10
batch_size:32
num_workers:8
gram_dim:64
mention_word_dim:32
margin:0.5
loss_func:cross_entropy
measure:ip
lr:1e-03
wd:1e-04
optim:adagrad
sparse:False
train_ent:False
train_word:False
train_linear:False
train_gram:True
train_mention:True
device:1