seed:-1
exp_name:yamada_include_everything
debug:False
data_path:/home/rogupta/wikinet_2/data
yamada_model:yamada_model.pickle
num_shards:100
gram_type:trigram
gram_vocab:vocab_trigram_266826.tsv
train_size:100000
query_size:5000
conll_split:dev
max_word_size:5
max_gram_size:40
max_context_size:200
max_ent_size:60
model:yamada
include_string:True
include_stats:True
include_word:True
include_gram:True
include_context:True
norm_gram:True
norm_word:True
norm_context:True
norm_final:True
cand_gen_rand:True
num_candidates:32
patience:2
num_epochs:25
batch_size:32
num_workers:8
gram_dim:64
margin:0.5
loss_func:cross_entropy
measure:ip
dp:0.3
hidden_size:1000
lr:1e-02
wd:1e-04
optim:adagrad
sparse:False
train_ent:True
train_word:True
train_linear:True
train_gram:True
device:0